# Generated by Django 4.0.3 on 2022-03-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyReport', '0002_players_player_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='player_positions',
            field=models.ManyToManyField(related_name='positions', to='MyReport.positions'),
        ),
    ]
