# Generated by Django 4.0.3 on 2022-03-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyReport', '0004_alter_players_player_positions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('player_positions', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='Players',
        ),
    ]
