# Generated by Django 4.0.3 on 2022-03-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyReport', '0005_players1_delete_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('player_positions', models.CharField(max_length=64)),
                ('team', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='Players1',
        ),
    ]
