# Generated by Django 4.0.3 on 2022-03-10 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyReport', '0007_teams_alter_players_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='team',
        ),
    ]
