# Generated by Django 4.0.3 on 2022-03-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyReport', '0009_teams1_delete_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_name', models.CharField(max_length=64)),
                ('athlete_name', models.CharField(max_length=64)),
                ('athlete_email', models.EmailField(max_length=254)),
                ('defense', models.CharField(max_length=1000)),
                ('offesence', models.CharField(max_length=1000)),
                ('work_ethic', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Teams1',
        ),
    ]
