# Generated by Django 4.0.3 on 2022-03-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyReport', '0011_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMG_Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
