# Generated by Django 4.0.3 on 2022-03-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyReport', '0012_img_teams_delete_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMG_Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('player_positions', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='Players',
        ),
    ]
