# Generated by Django 4.0.3 on 2022-03-17 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyReport', '0014_players_delete_img_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CoachName', models.CharField(max_length=64)),
                ('Defense', models.CharField(max_length=1000)),
                ('Hitting', models.CharField(max_length=1000)),
                ('Pitching', models.CharField(max_length=1000)),
                ('Character_Work_Ethic', models.CharField(max_length=1000)),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyReport.players')),
            ],
        ),
        migrations.DeleteModel(
            name='Reports',
        ),
    ]
